### PR TITLE
XSS

### PR DESCRIPTION
**Pull request by robertkowalski**
this needs #34 and #33 (hapi updates) merged before, they are included in this optimistic branch

### CODE REVIEW

**Comment by robertkowalski** [comment]
I like awesomesausage!

**Comment by robertkowalski** [comment]
Thanks for the suggestion, applied in 901c9c9 which i will squash before merging

**Comment by robin-drexler** [comment]
Lol, seems like Github also strip tags from comments. :D Actually I wrote: "How about having a title like `'awesome<script>alert('ente');</script>sausage'` and[...]", but forgot to put the title part in back ticks. Glad you still got my intention right. :D

**Comment by robertkowalski** [comment]
haha

**Comment by robertkowalski** [comment]
are we ready to go?

**Comment by robin-drexler** [comment]
Yes, sir. lgtm

**Comment by robertkowalski** [comment]
merged as f31409e924adf7c3148006f3b2798dcd06cbf48f c8152e6d12615f6863729c5dd2bce2db79b944a5 and 59944d24df9d835da6cede25397a3a7971c5ec8d

**Pull request closed without merging**
